# 欧拉芭蕾猫 技术参数介绍
  
更新时间：2026年07月10日11时35分26秒   

## 一、基本信息
| 项目 | 参数 |
|------|------|
| 品牌 | 欧拉（ORA） |
| 车型级别 | 纯电动紧凑型轿车 |
| 车身结构 | 4门5座三厢车 |
| 上市时间 | 2022年7月 |
## 二、动力系统
| 项目 | 参数 |
|------|------|
| 驱动方式 | 前置前驱 |
| 电机类型 | 永磁同步电机 |
| 最大功率 | **126 kW（171马力）** |
| 最大扭矩 | **250 N·m** |
| 最高车速 | **155 km/h** |
| 0-50km/h加速时间 | **3.8秒**（标准模式） |
## 三、电池与续航
### （一）标准续航版（401km）
| 项目 | 参数 |
|------|------|
| 电池类型 | **磷酸铁锂电池**（蜂巢能源） |
| 电池容量 | **49.92 kWh** |
| CLTC综合续航里程 | **401 km** |
### （二）长续航版（500km）
| 项目 | 参数 |
|------|------|
| 电池类型 | **磷酸铁锂电池**（蜂巢能源） |
| 电池容量 | **60.5 kWh** |
| CLTC综合续航里程 | **500 km** |
### （三）充电性能
- **快充时间**：30分钟（30%→80%，快充模式下）
- **慢充时间**：约8小时
- **快充接口位置**：右侧前翼子板
- **支持最大快充功率**：约60 kW
## 四、车身尺寸
| 项目 | 参数 |
|------|------|
|  长 ×  宽 ×  高（mm） | **4401 ×  1867 ×  1633 mm** |
轴距       (mm)          		*2710 mm*				|
> *注：表格中“ ”为占位符，实际数据如下：*
> - *车长：4401 mm*
> - *车宽：1867 mm*
> - *车高：1633 mm*
> - *轴距：2710 mm*
## （更正后表格）
车身尺寸：
-  长：4401 mm
-  宽：1867 mm
-  高：1633 mm
-  轴距：2710 mm
-  前轮距 /   后轮距    :    1583 mm /   1603 mm
最小离地间隙        :    150 mm
整备质量              :    约1560 kg (标准续航版) /   约1615 kg (长续航版)
##   五、底盘与悬架系统
转向系统          :    电动助力转向 (EPS)
前悬架类型        :    麦弗逊式独立悬架
后悬架类型        :    多连杆式独立悬架
制动系统 (前/后) :    通风盘式 /   盘式
驻车制动类型      :    电子驻车 (EPB)
轮胎规格          :    225/55 R18 (全系标配)
##   六、智能配置与安全系统
### ADAS智能驾驶辅助系统
自适应巡航控制(ACC)                    ✓ 
车道保持辅助(LKA)                     ✓ 
车道偏离预警(LDW)                     ✓ 
主动刹车/主动安全系统(AEB)            ✓ 
交通标志识别(TSR)                     ✓ 
360°全景影像                          ✓ 
倒车雷达                              ✓ 
自动泊车入位                          ✓ 
###   被动安全配置
主/副驾驶座安全气囊                   ✓ 
前排侧气囊                            ✓ 
前后排头部气囊(气帘)                  ✓ 
胎压监测装置                          ✓ 
ISOFIX儿童座椅接口                    ✓ 
##   七、舒适性与科技配置
液晶仪表盘尺寸                        10.25英寸  
中控液晶屏尺寸                        12.3英寸  
语音识别控制系统                      支持  
手机互联/映射                         支持  
OTA远程升级                           支持  
无钥匙启动                            支持  
无钥匙进入                            前排  
远程启动                              支持  
方向盘材质                            皮质  
座椅材质                             仿皮(皮质包裹)   
主驾驶座椅调节方式                    电动调节(6向)
副驾驶座椅调节方式                    电动调节(4向)
前排座椅加热                          选装   
车内氛围灯                            多色氛围灯   
空调控制方式                          自动空调   
后座出风口                            有   
PM2.5过滤装置                        有   
##   八、外观设计特色
复古造型设计，灵感来源于经典甲壳虫造型：
圆润车身线条                       圆灯设计                        镀铬保险杠装饰                   掀背式尾门                       多种复古配色可选               白璞玉      天青色      朝暮青      金风玉露等  
---
*以上数据仅供参考，具体配置以实际销售车型为准。*  

参考资料：   
fr.8dk9.cn <br>
3d.5gj6.cn <br>
ef.coin19.cn <br>
ch.8dk9.cn <br>
c8.otskb.cn <br>
wy.3r1y.cn <br>
sl.8dk9.cn <br>
a2.5vu8.cn <br>
dy.6gl8.pro <br>
p1.coin16.cn <br>